[tools]
prek = "latest"
rumdl = "latest"
shellcheck = "latest"

[settings]
experimental = true

[hooks]
enter = "bash ./scripts/enter_project.sh"

[env]
_.file = '.env'       # for sensitive data
UV_LINK_MODE = "copy"
