name: 💡 Feature Request
description: Suggest a new idea, enhancement, or improvement.
title: "[Feature]: "
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea clearly.

  - type: textarea
    id: motivation
    attributes:
      label: Problem or Motivation
      description: What problem does this solve, or what's the motivation behind it?
      placeholder: "Currently, there's no way to... This would help with..."
      validations:
        required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe the feature and how it should work.
      placeholder: |
        - Add functionality for...
        - Extend the API to support...
        - Example usage: ...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered other solutions? Why are they not ideal?

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references here.

  - type: checkboxes
    id: agreement
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project’s Code of Conduct.
          required: true
